blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/wiredoor/wiredoor/security/policy
    about: Please report security issues here.
  - name: Community Discussions
    url: https://github.com/wiredoor/wiredoor/discussions
    about: For ideas, questions or general help.
