name: Feature Request
description: Suggest a new idea or feature for Wiredoor
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving Wiredoor! Please describe your idea below.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      description: Describe the problem it solves or the use case.
  - type: textarea
    id: implementation
    attributes:
      label: Any implementation ideas?
      description: Optional thoughts on how this could be built.
